//ROOMS
export const GET_ROOMS = "GET_ROOMS";
export const STORE_CURRENT_ROOM = "STORE_CURRENT_ROOM";
export const LOG_ROOM_ERROR = "LOG_ROOM_ERROR";

export const GET_ROOMS_ERROR = "GET_ROOMS_ERROR";
export const CREATE_EDIT_ROOM_ERROR = "CREATE_EDIT_ROOM_ERROR";
export const DELETE_ROOM_ERROR = "DELETE_ROOM_ERROR";

//ATTENDEE

export const CREATE_ATTENDEE = "CREATE_ATTENDEE";
export const SEND_EMAIL = "SEND_EMAIL";
export const GET_ATTENDEE_LIST = "GET_ATTENDEE_LIST";
export const GET_ATTENDEE_DATA = "GET_ATTENDEE_DATA";
export const GET_ATTENDEE_LIST_FAIL = "GET_ATTENDEE_LIST_FAIL";
export const CREATE_EDIT_ATTENDEE_FAIL = "CREATE_EDIT_ATTENDEE_FAIL";
export const CREATE_EDIT_ATTENDEE_SUCCESS = "CREATE_EDIT_ATTENDEE_SUCCESS";
export const DELETE_ATTENDEE_FAIL = "DELETE_ATTENDEE_FAIL";

//SPEAKER
export const CREATE_SPEAKER = "CREATE_SPEAKER";
export const LOG_REGISTRATION_ERROR = "LOG_REGISTRATION_ERROR";
export const GET_SPEAKER_LIST = "GET_SPEAKER_LIST";
export const GET_SPEAKER_DATA = "GET_SPEAKER_DATA";
export const CREATE_SPEAKER_SUCCESS = "CREATE_SPEAKER_SUCCESS";
export const CREATE_SPEAKER_FAIL = "CREATE_SPEAKER_FAIL";
export const UPDATE_SPEAKER_SUCCESS = "UPDATE_SPEAKER_SUCCESS";
export const UPDATE_SPEAKER_FAIL = "UPDATE_SPEAKER_FAIL";
export const DELETE_SPEAKER_SUCCESS = "DELETE_SPEAKER_SUCCESS";
export const DELETE_SPEAKER_FAIL = "DELETE_SPEAKER_FAIL";

//Authentication

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const FORGET_PASSWORD = "FORGET_PASSWORD";

//EVENTS
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";
export const STORE_CURRENT_EVENT = "STORE_CURRENT_EVENT";

//SESSIONS
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_FAIL = "GET_SESSIONS_FAIL";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAIL = "CREATE_SESSION_FAIL";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAIL = "UPDATE_SESSION_FAIL";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
export const DELETE_SESSION_FAIL = "DELETE_SESSION_FAIL";
export const GET_SESSION_TYPE_LIST_SUCCESS = "GET_SESSION_TYPE_LIST_SUCCESS";

///QUESTION FORMS
export const GET_SESSIONS_BY_EVENT_ID = "GET_SESSIONS_BY_EVENT_ID";
export const LOG_FORM_ERROR = "LOG_FORM_ERROR";
export const STORE_FORMS = "STORE_FORMS";
export const STORE_CURRENT_FORM = "STORE_CURRENT_FORM";
export const GET_FORMS_ERROR = "GET_FORMS_ERROR";
export const CREATE_EDIT_FORM_ERROR = "CREATE_EDIT_FORM_ERROR";
export const DELETE_FORM_ERROR = "DELETE_FORM_ERROR";

////Attendance
export const LOG_ATTENDANCE_ERROR = "LOG_ATTENDANCE_ERROR";
export const STORE_ATTENDANCE_LIST = "STORE_ATTENDANCE_LIST";

///STATIC PAGES

export const STORE_ABOUT_US = "STORE_ABOUT_US";
export const STORE_ABOUT_ETERNUS = "STORE_ABOUT_ETERNUS";
export const STORE_HELPDESK_DETAILS = "STORE_HELPDESK_DETAILS";
export const STORE_EVENT_LOCATION = "STORE_EVENT_LOCATION";
export const LOG_STATIC_PAGE_ERROR = "LOG_STATIC_PAGE_ERROR";
export const GET_ABOUTUS_ERROR = "GET_ABOUTUS_ERROR";
export const CREATE_EDIT_ABOUTUS_ERROR = "CREATE_EDIT_ABOUTUS_ERROR";
export const GET_ABOUTETERNUS_ERROR = "GET_ABOUTETERNUS_ERROR";
export const CREATE_EDIT_ABOUTETERNUS_ERROR = "CREATE_EDIT_ABOUTETERNUS_ERROR";
export const GET_HELPDESK_ERROR = "GET_HELPDESK_ERROR";
export const CREATE_EDIT_HELPDESK_ERROR = "CREATE_EDIT_HELPDESK_ERROR";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";
export const CREATE_EDIT_LOCATION_ERROR = "CREATE_EDIT_LOCATION_ERROR";

//GET_SPONSORS
export const GET_SPONSORS = "GET_SPONSORS";
export const STORE_CURRENT_SPONSOR = "STORE_CURRENT_SPONSOR";
export const LOG_SPONSOR_ERROR = "LOG_SPONSOR_ERROR";
export const GET_SPONSOR_ERROR = "GET_SPONSOR_ERROR";
export const CREATE_EDIT_SPONSOR_ERROR = "CREATE_EDIT_SPONSOR_ERROR";
export const DELETE_SPONSOR_ERROR = "DELETE_SPONSOR_ERROR";

//ATTENDEE_COUNT
export const GET_ATTENDEE_COUNTS_SUCCESS = "GET_ATTENDEE_COUNTS_SUCCESS";
export const GET_ATTENDEE_COUNTS_FAIL = "GET_ATTENDEE_COUNTS_FAIL";

//PROFILE_LIST
export const GET_PROFILE_LIST_SUCCESS = "GET_PROFILE_LIST_SUCCESS";
export const GET_PROFILE_LIST_FAIL = "GET_PROFILE_LIST_FAIL";
export const GET_PROFILE_ARRAY_SUCCESS = "GET_PROFILE_ARRAY_SUCCESS";

//APPTHEME
export const GET_APPTHEME_SUCCESS = "GET_APPTHEME_SUCCESS";
export const GET_APPTHEME_FAIL = "GET_APPTHEME_FAIL";
export const CREATE_APPTHEME_SUCCESS = "CREATE_APPTHEME_SUCCESS";
export const CREATE_APPTHEME_FAIL = "CREATE_APPTHEME_FAIL";
export const UPDATE_APPTHEME_SUCCESS = "UPDATE_APPTHEME_SUCCESS";
export const UPDATE_APPTHEME_FAIL = "UPDATE_APPTHEME_FAIL";
export const STORE_CURRENT_APPTHEME = "STORE_CURRENT_APPTHEME";

//ATTENDEE BULK UPLOAD
export const LOG_BULk_UPLOAD_ERROR = "LOG_BULk_UPLOAD_ERROR";
export const CLEAR_BULk_UPLOAD_ERROR = "CLEAR_BULk_UPLOAD_ERROR";
export const LOG_BULk_VALIDATE_ERROR = "LOG_BULk_VALIDATE_ERROR";
export const CLEAR_BULk_VALIDATE_ERROR = "CLEAR_BULk_VALIDATE_ERROR";

//SESSIONQA
export const GET_SESSIONQA_ERROR = "GET_SESSIONQA_ERROR";
export const GET_SESSIONQA = "GET_SESSIONQA";

