const routes = {
  "/": "Home",
  "/dashboard": "Dashboard",
  "/events": "Events",
  "/roomsList/rooms": "Rooms",
  "/roomsList": "Rooms List",
  "/registration": "Registration",
  "/registrationList": "Attendee List",
  "/registrationList/registration": "Attendee Registration",
  "/questionForms": "Question Forms",
  "/dynamicForms": "Dynamic Forms",
  "/dynamicForms/questionForms": "Question Forms",
  "/attendance": "Attendance",
  "/staticPages": "Static Pages",
  "/staticPages/aboutUs": "About Us",
  "/staticPages/aboutEternus": "About Eternus",
  "/staticPages/helpDesk": "Help Desk",
  "/staticPages/eventLocation": "Event Location",
  "/sponsors": "Sponsors List",
  "/sponsors/sponsorForm": "Sponsor Form",
  "/reports": "Reports",
  "/reports/eventReports": "Event Reports",
  "/reports/attendeeReports": "Attendee Reports",
  "/reports/sessionReports": "Session Reports",
  "/events/EventForm": "Add Event",
  "/speakers": "Speakers List",
  "/speakers/speakerForm": "Speakers Registration",
  "/profiles": "Profiles List",
  "/profiles/profileForm": "Add Profile",
  "/sessions": "Sessions"
};
export default routes;
